version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: hourly
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: hourly
  - package-ecosystem: npm
    directory: "/vue"
    schedule:
      interval: hourly

