run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dogsled
    - exportloopref
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - revive
    - typecheck
    - unconvert
    - unused
    - misspell
    - nolintlint
