run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - deadcode 
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint 
    - exhaustive 
    - exportloopref
    - goconst
    - gocritic 
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec 
    - gosimple 
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint 
    - paralleltest
    - promlinter
    - revive 
    - staticcheck
    - stylecheck 
    - tenv
    - testpackage
    - thelper 
    - typecheck
    - unconvert
    - unparam 
    - unused 
    - varcheck 
    - whitespace

